import "./globals.css";
import { Helmet } from "react-helmet-async";

export default function RootLayout({ children }) {
  return (
    <>
      <Helmet>
        <title>RhizAgain - Urban Nature Chatbot</title>
        <meta
          name="description"
          content="Generated by the best grad team in the world."
        />
      </Helmet>
      <div className="antialiased">
        {children}
      </div>
    </>
  );
}